from src.config.llm_factory import get_llm
from settings import Settings as ENV
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage, BaseMessage, ToolMessage
from langchain_core.runnables.config import RunnableConfig
from langgraph.graph import StateGraph, MessagesState, START, END
# from langsmith import traceable
from pydantic import BaseModel, Field
from src.prompts import load_prompt
from src.models.workflow import WorkflowInput
from src.utils.normalize import normalize_llm_markdown
from src.services.conversation_service import (
    conversation_create_item, conversation_list_items, conversation_items_to_history
)
from src.tools.image_send_tool import (
    send_computer_department_room_image, send_su_map_image, send_channels_submit_complaints_image,
    send_calendar_image, send_graduated_image, send_step_image,
    send_office_hours_image, send_registration_officer_image,
)
from src.tools.rag_document_search_tool import (
    faq_search_tool, academic_search_tool, finance_search_tool, staff_search_tool
)
from typing import Literal
import logging
import asyncio
from dataclasses import dataclass

@dataclass
class WorkflowResult:
    text: str
    image_urls: list[str]


logger = logging.getLogger(__name__)


# ==================== Search Tool Names (early-exit triggers) ====================
SEARCH_TOOL_NAMES = frozenset({
    "faq_search_tool", "academic_search_tool", "finance_search_tool", "staff_search_tool"
})


# ==================== Custom State ====================
class AgentState(MessagesState):
    """Extended state that keeps routing decision separate from messages."""
    route: str


# ==================== Structured Router Output ====================
class RouteDecision(BaseModel):
    """Structured output for the router LLM."""
    agent: Literal["general_agent", "academic_agent", "finance_agent", "staff_agent"] = Field(
        description="The agent best suited to handle the user's query"
    )


# ==================== LLM Instances ====================
router_llm = get_llm(model_name=ENV.LLM_MODEL_NAME, temperature=0.0, num_ctx=8192, num_predict=32)
agent_llm_strict = get_llm(model_name=ENV.LLM_MODEL_NAME, temperature=0.3, num_ctx=8192, num_predict=2048)


# ==================== Tool Sets per Agent ====================
GENERAL_TOOLS = [
    faq_search_tool,
    send_su_map_image,
    send_channels_submit_complaints_image,
    send_computer_department_room_image,
]

ACADEMIC_TOOLS = [
    academic_search_tool,
    send_calendar_image,
    send_graduated_image,
    send_step_image,
]

FINANCE_TOOLS = [
    finance_search_tool,
]

STAFF_TOOLS = [
    staff_search_tool,
    send_office_hours_image,
    send_registration_officer_image,
]


# ==================== Custom Agent Runner (Early Exit for Search Tools) ====================
async def _run_agent_with_early_exit(llm, tools: list, system_prompt: str, messages: list, config: dict) -> str:
    """Run agent with early exit for search tools.
    
    - If a search tool is called → execute tool → return tool result directly (skip re-generation)
    - If an image tool is called → execute tool → continue agent loop for text response
    - If direct response (no tool call) → return as-is
    """
    tool_map = {t.name: t for t in tools}
    system_msg = SystemMessage(content=system_prompt)
    llm_with_tools = llm.bind_tools(tools)
    
    current_messages = [system_msg] + list(messages)
    
    max_iterations = 5  # Safety guard against infinite loops
    for _ in range(max_iterations):
        response = await llm_with_tools.ainvoke(current_messages, config=config)
        
        import re
        import json
        import uuid
        
        tool_calls = response.tool_calls
        if not tool_calls and response.content:
            # Fallback: parse markdown tool_call generated by LLM instead of native binding
            pattern = re.compile(r'```(?:tool_call|json)?\s*({.*?})\s*```', re.DOTALL)
            matches = pattern.finditer(response.content)
            for match in matches:
                try:
                    parsed = json.loads(match.group(1))
                    if "name" in parsed:
                        tool_calls.append({
                            "name": parsed["name"],
                            "args": parsed.get("parameters", parsed.get("args", {})),
                            "id": str(uuid.uuid4()),
                            "type": "tool_call"
                        })
                except Exception:
                    pass
            
            # Additional fallback: check if the entire content is just a JSON object
            if not tool_calls:
                try:
                    parsed = json.loads(response.content.strip())
                    if "name" in parsed:
                        tool_calls.append({
                            "name": parsed["name"],
                            "args": parsed.get("parameters", parsed.get("args", {})),
                            "id": str(uuid.uuid4()),
                            "type": "tool_call"
                        })
                except Exception:
                    pass

        if not tool_calls:
            # Direct response (chit-chat, safety, parameter-asking, etc.)
            return response.content
        
        # Execute all tool calls
        tool_messages = []
        search_result = None
        
        for tc in tool_calls:
            tool_name = tc["name"]
            tool_fn = tool_map.get(tool_name)
            if tool_fn is None:
                logger.warning(f"[Agent] Unknown tool called: {tool_name}")
                tool_messages.append(ToolMessage(
                    content=f"Error: Unknown tool '{tool_name}'",
                    tool_call_id=tc["id"]
                ))
                continue
                
            try:
                tool_config = {
                    **config,
                    "metadata": {
                        **config.get("metadata", {}),
                        "chat_history": messages[-5:-1] 
                    }
                }
                result = await tool_fn.ainvoke(tc["args"], config=tool_config)
            except Exception as e:
                logger.error(f"[Agent] Tool '{tool_name}' error: {e}")
                result = f"Error executing tool: {e}"
            
            tool_messages.append(ToolMessage(
                content=str(result),
                tool_call_id=tc["id"]
            ))
            
            # If a search tool was called, capture result for early exit
            if tool_name in SEARCH_TOOL_NAMES:
                search_result = str(result)
        
        if search_result is not None:
            # Search tool was called → summarize_agent already generated the final answer
            # Return directly, skip the agent's re-generation step
            logger.info("[Agent] Early exit: returning search tool result directly (skipping re-generation)")
            return search_result
        
        # Non-search tools (image tools) → continue loop for agent to generate text
        current_messages = current_messages + [response] + tool_messages
    
    logger.warning("[Agent] Max iterations reached, returning last response")
    return "ขออภัยครับ ระบบประมวลผลนานเกินไป กรุณาลองใหม่อีกครั้งนะครับ"


# ==================== Agent Node Factories ====================
def _make_agent_node(llm, tools: list, prompt_name: str):
    """Create a LangGraph node function for a specialized agent."""
    system_prompt = load_prompt(prompt_name)
    
    async def agent_node(state: AgentState, config: RunnableConfig) -> dict:
        response_text = await _run_agent_with_early_exit(
            llm=llm,
            tools=tools,
            system_prompt=system_prompt,
            messages=state["messages"],
            config=config,
        )
        if not response_text or response_text.strip() == "":
            return {"messages": [AIMessage(content="ไม่สามารถประมวลผลคำตอบได้ กรุณาลองใหม่อีกครั้งครับ")]}
        
        return {"messages": [AIMessage(content=response_text)]}
    
    return agent_node


# ==================== Router (Supervisor) ====================
async def classify_intent(state: AgentState) -> dict:
    """Use structured output to classify which agent should handle the user query.
    
    Stores the routing decision in state['route'] instead of polluting messages.
    Falls back to text parsing if structured output is not supported.
    """
    router_prompt = load_prompt("router_agent")
    messages = [SystemMessage(content=router_prompt)] + state["messages"]

    try:
        # Try structured output first
        structured_llm = router_llm.with_structured_output(RouteDecision)
        response = await structured_llm.ainvoke(messages)
        logger.info(f"[Router] Structured output: {response.agent}")
        return {"route": response.agent}
    except (Exception) as e:
        # Fallback for providers that don't support structured output
        logger.warning(f"[Router] Structured output not supported, falling back to text parsing: {e}")
        response = await router_llm.ainvoke(messages)
        return {"route": _parse_route_from_text(response.content)}


def _parse_route_from_text(content: str) -> str:
    """Parse agent name from free-text LLM response (fallback parser).
    
    More robust than simple 'in' checks — handles variations like
    'academic_agent', 'Academic Agent', 'ACADEMIC', etc.
    """
    content_lower = content.lower().strip()

    # Try exact match first
    for agent_name in ["academic_agent", "finance_agent", "staff_agent", "general_agent"]:
        if agent_name in content_lower:
            return agent_name

    # Try keyword match as fallback
    if "academic" in content_lower:
        return "academic_agent"
    elif "finance" in content_lower:
        return "finance_agent"
    elif "staff" in content_lower:
        return "staff_agent"
    
    return "general_agent"


def route_to_agent(state: AgentState) -> Literal[
    "general_agent", "academic_agent", "finance_agent", "staff_agent"
]:
    """Route to the correct agent based on the structured routing decision."""
    route = state.get("route", "general_agent")
    logger.info(f"[Router] Routing to: {route}")
    return route


# ==================== Build LangGraph Workflow ====================
workflow = StateGraph(AgentState)

# Add nodes
workflow.add_node("router", classify_intent)
workflow.add_node("general_agent", _make_agent_node(agent_llm_strict, GENERAL_TOOLS, "general_agent"))
workflow.add_node("academic_agent", _make_agent_node(agent_llm_strict, ACADEMIC_TOOLS, "academic_agent"))
workflow.add_node("finance_agent", _make_agent_node(agent_llm_strict, FINANCE_TOOLS, "finance_agent"))
workflow.add_node("staff_agent", _make_agent_node(agent_llm_strict, STAFF_TOOLS, "staff_agent"))

# Add edges
workflow.add_edge(START, "router")
workflow.add_conditional_edges("router", route_to_agent, {
    "general_agent": "general_agent",
    "academic_agent": "academic_agent",
    "finance_agent": "finance_agent",
    "staff_agent": "staff_agent",
})
workflow.add_edge("general_agent", END)
workflow.add_edge("academic_agent", END)
workflow.add_edge("finance_agent", END)
workflow.add_edge("staff_agent", END)

# Compile the graph
graph = workflow.compile()


# ==================== Run Workflow ====================
def _extract_final_response(result_messages: list) -> str:
    """Extract the final user-facing AI response from the message list.
    
    Filters out:
    - ToolMessages (tool call results)
    - AIMessages with empty content (tool-calling intermediate steps)
    - AIMessages that are just agent names (router artifacts)
    """
    agent_names = {"general_agent", "academic_agent", "finance_agent", "staff_agent"}

    for msg in reversed(result_messages):
        if not isinstance(msg, AIMessage):
            continue
        # Skip messages with no content (tool-call-only messages)
        if not msg.content or not msg.content.strip():
            continue
        # Skip messages that are just routing decisions
        if msg.content.strip().lower() in agent_names:
            continue
        # Skip messages with tool_calls (intermediate steps)
        if hasattr(msg, "tool_calls") and msg.tool_calls:
            continue
        return msg.content

    return "ไม่สามารถประมวลผลคำตอบได้ กรุณาลองใหม่อีกครั้งครับ"


# @traceable(name="CPSU-Chatbot", metadata={"source": "Webhook"})
async def run_workflow(workflow_input: WorkflowInput, timeout_seconds: int = 1200) -> WorkflowResult:
    """Run agent workflow with LangSmith tracing and timeout."""

    async def _run() -> WorkflowResult:
        # Build conversation history
        items_history = await conversation_list_items(
            user_id=workflow_input.user_id,
            platform=workflow_input.platform
        )
        conversation_history: list[BaseMessage] = conversation_items_to_history(items_history)

        # Limit conversation history to the last 4 messages (2 interactions back-and-forth)
        # to prevent model hallucinations and save context window.
        conversation_history = conversation_history[-4:]

        # Add current user message
        current_message = HumanMessage(content=workflow_input.input_as_text)
        all_messages = conversation_history + [current_message]

        final_response = None
        pending_images = []
        try:
            logger.info("[Router] Running LangGraph workflow...")

            run_metadata = {
                "user_id": workflow_input.user_id,
                "session_id": workflow_input.conversation_id,
                "platform": workflow_input.platform,
                "input": workflow_input.input_as_text,
                "pending_images": pending_images,
            }

            result = await graph.ainvoke(
                {"messages": all_messages},
                config={"metadata": run_metadata,
                "recursion_limit": 10}
            )

            result_messages = result.get("messages", [])
            final_response = _extract_final_response(result_messages)
            final_response = normalize_llm_markdown(final_response)

            return WorkflowResult(text=final_response, image_urls=pending_images)

        finally:
            # Save conversation to Redis
            save_items = [
                {"role": "user", "content": workflow_input.input_as_text}
            ]
            if final_response is not None:
                save_items.append({"role": "assistant", "content": final_response})

            await conversation_create_item(
                user_id=workflow_input.user_id,
                platform=workflow_input.platform,
                items=save_items
            )

    try:
        return await asyncio.wait_for(_run(), timeout=timeout_seconds)
    except asyncio.TimeoutError:
        logger.error(f"Workflow timeout after {timeout_seconds}s for user {workflow_input.user_id}")
        raise TimeoutError(f"Request timed out after {timeout_seconds} seconds")
