from typing import List, Dict, Any
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import BaseMessage
from langchain_core.runnables.config import RunnableConfig
from langchain_core.output_parsers import StrOutputParser
# from langsmith import traceable
from src.tools.image_send_tool import send_academic_staff_image
from src.config.llm_factory import get_llm
from src.prompts import load_prompt
from settings import Settings as ENV
import logging
import difflib


logger = logging.getLogger(__name__)


_summarizer_llm = get_llm(model_name=ENV.LLM_MODEL_NAME, temperature=0.3, top_p=0.95, num_ctx=8192, num_predict=2048)
_summarizer_instructions = load_prompt("summarize_agent")
_summarizer_staff_instructions = load_prompt("summarize_staff_agent")
_summarizer_prompt_template = ChatPromptTemplate.from_messages([
    ("system", "{instructions}"),
    MessagesPlaceholder(variable_name="chat_history"),
    ("user", "### Context\n{context}\n\n### Question\n{question}")
])
_summarizer_chain = _summarizer_prompt_template | _summarizer_llm | StrOutputParser()
_summarizer_staff_chain = _summarizer_prompt_template | _summarizer_llm.bind_tools([send_academic_staff_image])


# @traceable(name="summarizer_agent")
async def summarize_context(
    user_question: str, 
    actual_question: str, 
    retrieved_docs: List[Dict[str, Any]],
    chat_history: List[BaseMessage] = []
) -> str:
    """Synthesize a concise answer from retrieved documents using a dedicated LLM.
    
    This offloads document processing from the main agent, keeping its context small.
    
    Args:
        user_question: The LLM generated question.
        actual_question: The original user question.
        retrieved_docs: List of dicts with 'content' and 'score' keys from retrieval.
        
    Returns:
        A synthesized answer.
    """
    if not retrieved_docs:
        return ""

    retrieved_text  = "\n\n".join(
        f"{doc['content']}"
        for doc in retrieved_docs
    )

    try:

        answer = await _summarizer_chain.ainvoke({
            "instructions": _summarizer_instructions,
            "chat_history": chat_history,
            "context": retrieved_text,
            "question": f"- {user_question}\n- {actual_question}"
        })

        answer = answer.strip()
        if not answer or answer.startswith("NOT_") or answer in ["NOT_FOUND"]:
            logger.info("[Summarizer Agent] No relevant info found in documents")
            return ""
        similarity = difflib.SequenceMatcher(None, answer, "NOT_FOUND").ratio()
        if similarity >= 0.8 or not answer:
            logger.info("[Summarizer Agent] No relevant info found in documents")
            return ""

        logger.info("[Summarizer Agent] Generated summary (%d chars from %d docs)", len(answer), len(retrieved_docs))
        return answer

    except Exception as e:
        logger.error("[Summarizer Agent] Error generating answer: %s", e)
        # Fallback
        return "ไม่สามารถประมวลผลคำตอบได้ กรุณาลองใหม่อีกครั้งครับ"
    

# @traceable(name="summarizer_staff_agent")
async def summarize_staff_context(
    user_question: str, 
    actual_question: str, 
    retrieved_docs: List[Dict[str, Any]],
    config: RunnableConfig,
    chat_history: List[BaseMessage] = []
) -> str:
    """Synthesize a concise answer from retrieved documents using a dedicated LLM.
    
    This offloads document processing from the main agent, keeping its context small.
    
    Args:
        user_question: The LLM generated question.
        actual_question: The original user question.
        retrieved_docs: List of dicts with 'content' and 'score' keys from retrieval.
        
    Returns:
        A synthesized answer.
    """
    if not retrieved_docs:
        return ""

    retrieved_text  = "\n\n".join(
        f"{doc['content']}"
        for doc in retrieved_docs
    )

    try:

        response = await _summarizer_staff_chain.ainvoke({
            "instructions": _summarizer_staff_instructions,
            "chat_history": chat_history,
            "context": retrieved_text,
            "question": f"- {user_question}\n- {actual_question}"
        }, config=config)

        import re
        import json
        import uuid

        tool_calls = response.tool_calls
        answer = response.content.strip() if response.content else ""

        if not tool_calls and response.content:
            # Fallback: parse markdown tool_call generated by LLM instead of native binding
            pattern = re.compile(r'```(?:tool_call|json)?\s*({.*?})\s*```', re.DOTALL)
            matches = pattern.finditer(response.content)
            for match in matches:
                try:
                    parsed = json.loads(match.group(1))
                    if "name" in parsed:
                        answer = "ดูรูปภาพเพิ่มเติมได้เลยค้าบบ"
                        tool_calls.append({
                            "name": parsed["name"],
                            "args": parsed.get("parameters", parsed.get("args", {})),
                            "id": str(uuid.uuid4()),
                            "type": "tool_call"
                        })
                except Exception:
                    pass
            
            # Additional fallback: check if the entire content is just a JSON object
            if not tool_calls:
                try:
                    parsed = json.loads(response.content.strip())
                    if "name" in parsed:
                        answer = "ดูรูปภาพเพิ่มเติมได้เลยค้าบบ"
                        tool_calls.append({
                            "name": parsed["name"],
                            "args": parsed.get("parameters", parsed.get("args", {})),
                            "id": str(uuid.uuid4()),
                            "type": "tool_call"
                        })
                except Exception:
                    pass

        if hasattr(response, "tool_calls") and tool_calls:
            for tc in tool_calls:
                if tc["name"] == "send_academic_staff_image":
                    try:
                        await send_academic_staff_image.ainvoke(tc["args"], config=config)
                    except Exception as e:
                        logger.error("[Summarizer Staff Agent] Tool execution error: %s", e)

        if not answer or answer.startswith("NOT_") or answer in ["NOT_FOUND"]:
            logger.info("[Summarizer Staff Agent] No relevant info found in documents")
            return ""
        
        similarity = difflib.SequenceMatcher(None, answer, "NOT_FOUND").ratio()
        if similarity >= 0.8:
            logger.info("[Summarizer Staff Agent] No relevant info found in documents (similarity check)")
            return ""

        logger.info("[Summarizer Staff Agent] Generated summary (%d chars from %d docs)", len(answer), len(retrieved_docs))
        return answer

    except Exception as e:
        logger.error("[Summarizer Staff Agent] Error generating answer: %s", e)
        # Fallback
        return "ไม่สามารถประมวลผลคำตอบได้ กรุณาลองใหม่อีกครั้งครับ"